### PR TITLE
Moved Test projects to Tests directory

### LINKED ISSUE #108: move the tests and their contents to their own folder
Move anything that references a test - including the demo program - to a folder called `tests` or similar

### PR DESCRIPTION
**Pull request by Druffl3**
Closes #108 

Created a "Tests" directory and Moved these test projects inside it.

- DragonFruit.Six.API.Tests
- DragonFruit.Six.API.Tests.Common
- DragonFruit.Six.API.Demo

### CODE REVIEW

**Comment by aspriddell** [comment]
ok so i've updated the tests.yaml on your fork but in future you should create a branch instead of using the master branch.

**Review by aspriddell — CHANGES_REQUESTED** [review]
personally, i think it would be better as all lowercase (`tests`), so it matches with `res`

**Comment by Druffl3** [comment]
Okay, will make it lowercase and will make sure to create a branch going forward.

**Comment by aspriddell** [comment]
for now, don't worry about the master branch thing, ping me when you're done (currently the old folder still exists) - you need to do this on a desktop and not in github web

**Comment by aspriddell** [comment]
@Druffl3 you planning on making the changes? From what i can see from the web the folder is still in title case:

image

just needs cloning, decapitalising then pushing back.

**Comment by aspriddell** [comment]
closing as no action has been taken in 30+ days and I want to change the test framework anyway.

**Pull request closed without merging**
